-- update the salary when the hourly pay is updated
-- create trigger salary_calculate
-- before update on employees
-- for each row
-- set new.salary=(new.hourly_pay*8*30);
-- updating after cost table to each change in salaries of employee table
-- create trigger total_salary
-- before update on cost
-- for each row
-- set new.expenses=